# Generated by Django 5.2.8 on 2025-11-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('teclados', 'Teclados'), ('mouses', 'Mouses'), ('auriculares', 'Auriculares'), ('monitores', 'Monitores')], max_length=20),
        ),
    ]
