# Generated by Django 5.2.8 on 2025-11-10 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_total_amount_order_total_order_mercadopago_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item de Orden', 'verbose_name_plural': 'Items de Orden'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='shippingoption',
            options={'ordering': ['price'], 'verbose_name': 'Opción de Envío', 'verbose_name_plural': 'Opciones de Envío'},
        ),
        migrations.AlterModelOptions(
            name='shippingzone',
            options={'ordering': ['name'], 'verbose_name': 'Zona de Envío', 'verbose_name_plural': 'Zonas de Envío'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mercadopago_id',
            field=models.CharField(blank=True, help_text='ID de la transacción en MercadoPago', max_length=100, null=True, verbose_name='ID de MercadoPago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado actual de la orden', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total de la orden en pesos', max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio en el momento de la compra', max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Cantidad del producto en la orden', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='¿El producto está disponible para la venta?', verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('teclados', 'Teclados Mecánicos'), ('mouses', 'Mouses Gaming'), ('auriculares', 'Auriculares'), ('monitores', 'Monitores Gaming')], help_text='Categoría del producto', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Descripción detallada del producto', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Imagen principal del producto', upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo del producto', max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos argentinos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock Disponible'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada del envío', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='estimated_days',
            field=models.CharField(help_text='Tiempo estimado de entrega', max_length=50, verbose_name='Días Estimados'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿Esta opción de envío está disponible?', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo de la opción de envío', max_length=100, verbose_name='Nombre del Envío'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Costo del envío en pesos', max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='name',
            field=models.CharField(help_text='Nombre de la zona geográfica', max_length=100, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='postal_code_end',
            field=models.CharField(help_text='Fin del rango de códigos postales', max_length=10, verbose_name='Código Postal Fin'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='postal_code_start',
            field=models.CharField(help_text='Inicio del rango de códigos postales', max_length=10, verbose_name='Código Postal Inicio'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='shipping_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.shippingoption', verbose_name='Opción de Envío'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='marketplace_status_6b27f5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='marketplace_created_b4d26a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='marketplace_email_5e5200_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'available'], name='marketplace_categor_d453d8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='marketplace_created_1f132e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='marketplace_price_34d50e_idx'),
        ),
    ]
